/**
 * ArchitectAgent — Implementation
 *
 * Converts natural-language intent into a structured module blueprint (ParsedIntent).
 * Uses ContextEngine via AgentToolkit to explore existing codebase before designing.
 *
 * Contract: Architect NEVER produces executable code — only TypeScript interfaces.
 * The Coder agent reads the ArchitectOutput and implements against those contracts.
 *
 * @security Output must be validated before passing to Coder — use Zod schema.
 */

import type { ILLMGateway } from '../../src/core/llm/LLMGateway.types.js';
import type { IAgentToolkit } from '../../src/core/llm/AgentToolkit.types.js';
import type {
  IArchitectAgent,
  ParsedIntent,
  ArchitectOutput,
} from './architect.types.js';
import type { AgentId } from '../../core/orchestrator.types.js';
import { ARCHITECT_SYSTEM_PROMPT } from './prompts.js';

const AGENT_ID = 'architect-v1' as unknown as AgentId;
const MODEL = 'claude-sonnet-4-6';
const MAX_TOKENS = 4096;

export class ArchitectAgent implements IArchitectAgent {
  readonly #gateway: ILLMGateway;
  readonly #toolkit: IAgentToolkit;

  constructor(gateway: ILLMGateway, toolkit: IAgentToolkit) {
    this.#gateway = gateway;
    this.#toolkit = toolkit;
    gateway.registerTools([...toolkit.getTools()]);
  }

  async parseIntent(raw: string): Promise<ParsedIntent> {
    const response = await this.#gateway.complete(
      [{ role: 'user', content: raw }],
      { system: ARCHITECT_SYSTEM_PROMPT, model: MODEL, maxTokens: MAX_TOKENS },
    );
    return this.#parseJSON(response.content, raw);
  }

  async designModules(intent: ParsedIntent): Promise<ArchitectOutput> {
    const prompt =
      `Based on this parsed intent, produce the final module blueprint.\n\n` +
      `Intent summary: ${intent.summary}\n\n` +
      `Modules to design: ${intent.modules.map((m) => m.name).join(', ')}\n\n` +
      `Return JSON matching the ParsedIntent schema with completed interfaces.`;

    const response = await this.#gateway.complete(
      [{ role: 'user', content: prompt }],
      { system: ARCHITECT_SYSTEM_PROMPT, model: MODEL, maxTokens: MAX_TOKENS },
    );

    const refined = this.#parseJSON(response.content, intent.raw);
    return {
      agentId: AGENT_ID,
      intent: refined,
      artifacts: refined.modules.map((m) => ({
        type: 'file' as const,
        path: m.path,
        content: this.#renderInterfaces(m.name, m.interfaces),
      })),
    };
  }

  // ── Private ─────────────────────────────────────────────────────────────────

  #parseJSON(content: string, raw: string): ParsedIntent {
    const json = extractJSON(content);
    const parsed = JSON.parse(json) as Partial<ParsedIntent>;
    return {
      raw: parsed.raw ?? raw,
      summary: parsed.summary ?? '',
      modules: parsed.modules ?? [],
      dependencies: parsed.dependencies ?? [],
    };
  }

  #renderInterfaces(
    moduleName: string,
    interfaces: ParsedIntent['modules'][number]['interfaces'],
  ): string {
    const lines = [`/** ${moduleName} — generated by ArchitectAgent */`];
    for (const iface of interfaces) {
      lines.push(`export interface ${iface.name} {`);
      for (const f of iface.fields) {
        const opt = f.optional ? '?' : '';
        const ro = f.readonly ? 'readonly ' : '';
        const doc = f.description ? `  /** ${f.description} */\n` : '';
        lines.push(`${doc}  ${ro}${f.name}${opt}: ${f.type};`);
      }
      lines.push('}', '');
    }
    return lines.join('\n');
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Extract JSON from LLM response — strips markdown code fences if present */
function extractJSON(text: string): string {
  const fenced = /```(?:json)?\s*([\s\S]+?)```/.exec(text);
  if (fenced) return fenced[1]!.trim();
  const brace = text.indexOf('{');
  if (brace !== -1) return text.slice(brace);
  return text.trim();
}
